### ISSUE TITLE
error compicc

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compicc#1]
[compiz_crash-7732.txt](https://github.com/compiz-reloaded/compicc/files/1309528/compiz_crash-7732.txt)

**Comment by soreau** [comment]
It appears to be crashing in liboyranos used by compicc plugin. Closing this issue since liboyranos is not part of the compiz-reloaded suite.

**Comment by ethus3h** [comment]
(I think this might be a regression in Oyranos, it used to work for me.)
