### ISSUE TITLE
Doesnt compile

### ISSUE THREAD

**Issue by GavinDarkglider** [compiz-reloaded/compicc#8]
Running gentoo, the version from git throws errors, possibly due to typos's.

**Comment by ethus3h** [comment]
Hi! I can reproduce this, looking into it now. Thank you for reporting!

**Comment by ethus3h** [comment]
Please try: `emerge =media-libs/oyranos-9999`, then re-emerge compicc. It built for me after updating Oyranos in this manner. Thanks! :)

**Comment by GavinDarkglider** [comment]
That fixed the issue.
